# fly.toml app configuration file generated for smartpay on 2023-10-13T01:44:14-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "smartpay"
primary_region = "eze"

[build]
  builder = "paketobuildpacks/builder:base"
  buildpacks = ["gcr.io/paketo-buildpacks/go"]
  [build.args]
    BP_KEEP_FILES = "assets/*:public/*"

[[services]]
  protocol = "tcp"
  internal_port = 8080

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = "10s"
    timeout = "2s"
